### ISSUE TITLE
Have a tech report or paper?

### ISSUE THREAD

**Issue by daixiangzi** [lucasjinreal/LLaVA-Magvit2#1]

**Comment by lucasjinreal** [comment]
Hi, thanks for your interest to the work. Currently just a side project for exporation. We will update result once we got model trained.

**Comment by yangdongchao** [comment]
> Hi, thanks for your interest to the work. Currently just a side project for exporation. We will update result once we got model trained.

It means that your project is not successful in the stage?

**Comment by daixiangzi** [comment]
> Hi, thanks for your interest to the work. Currently just a side project for exporation. We will update result once we got model trained.

ok,Looking forward to hearing good news.
